SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Actor]
(
  [ActorId] [uniqueidentifier] NOT NULL,
  [actor_name] [nvarchar](255) NOT NULL,
  [created_at] [datetimeoffset](7) NULL
)
AS NODE ON [PRIMARY]
GO
ALTER TABLE [dbo].[Actor] ADD PRIMARY KEY CLUSTERED 
(
	[ActorId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[Actor] ADD UNIQUE NONCLUSTERED 
(
	[actor_name] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [GRAPH_UNIQUE_INDEX_93A0E0D3D64B42E0B807E04E8BEC65D8] ON [dbo].[Actor]
(
	$node_id
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [idx_Actor_Name] ON [dbo].[Actor]
(
	[actor_name] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Actor] ADD  DEFAULT (newid()) FOR [ActorId]
GO
ALTER TABLE [dbo].[Actor] ADD  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO
