SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EvidenceLink]
(
  [connection_reason] [nvarchar](255) NULL,
  [ai_confidence] [float] NULL,
  [link_metadata_json] [nvarchar](max) NULL
)
AS EDGE ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [GRAPH_UNIQUE_INDEX_8CEAEB95C01945A4BB18B61404BF786F] ON [dbo].[EvidenceLink]
(
	$edge_id
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_EvidenceLink_Graph] ON [dbo].[EvidenceLink]
(
	$from_id,
	$to_id
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
