-- Author: Bria Tran
-- Date: November 30th, 2025
-- Populates the database with essential starting data, 
-- including system roles and the initial system administrator account

-- Insert Roles
INSERT INTO roles (role_id, role_name) VALUES (1, 'EVAIDE_ADMIN');
INSERT INTO roles (role_id, role_name) VALUES (2, 'ORG_ADMIN');
INSERT INTO roles (role_id, role_name) VALUES (3, 'AGENT');

-- Insert Root Organization
INSERT INTO organizations (name, description, is_active) 
VALUES ('EVAIDE Central Administration', 'Root organization.', 1);

-- Insert Initial Admin using a bcrypt hash
-- Hash generated by backend
INSERT INTO users (email, password_hash, first_name, last_name, org_id, role_id, is_enabled, is_profile_complete) 
VALUES (
    'admin@evaide.com', 
    '$2b$12$ctpUfm5cDzD1WtAXQG/7A.QSuWsZguXVXterofw.kjZhZJVymKsqi',
    'System', 
    'Admin', 
    (SELECT TOP 1 org_id FROM organizations WHERE name = 'EVAIDE Central Administration'), 
    1, 1, 1 -- sets these columns role_id, is_enabled, is_profile_complete
);