SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Knows]
(
  [relationship_type] [nvarchar](100) NULL,
  [created_at] [datetimeoffset](7) NULL
)
AS EDGE ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [GRAPH_UNIQUE_INDEX_5E427C89340342E3989D845FD62A6470] ON [dbo].[Knows]
(
	$edge_id
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_Knows_Graph] ON [dbo].[Knows]
(
	$from_id,
	$to_id
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Knows] ADD  DEFAULT ('Acquaintance') FOR [relationship_type]
GO
ALTER TABLE [dbo].[Knows] ADD  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO
